# Generated by Django 5.1.1 on 2024-11-09 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.ForeignKey(db_column='assumee_user_id', limit_choices_to={'is_assumee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='following_assumptors', to=settings.AUTH_USER_MODEL)),
                ('following_id', models.ForeignKey(db_column='assumptor_user_id', limit_choices_to={'is_assumptor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='followers_assumees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follow',
                'unique_together': {('follower_id', 'following_id')},
            },
        ),
    ]
