# Generated by Django 5.1.1 on 2024-11-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={},
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='user_account',
        ),
    ]
