# Generated by Django 5.1.1 on 2024-11-13 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_useraccount_options_alter_useraccount_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_status',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='user_app_declined_at',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='user_reason',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='OrderListing',
            fields=[
                ('order_id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_status', models.CharField(default='PENDING', max_length=255)),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('order_udpated_at', models.DateTimeField()),
                ('list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.listing')),
                ('offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.offer')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_listing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_listing',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
