# Generated by Django 5.1.1 on 2024-12-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_refundrequest_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='paypal_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
