# Generated by Django 5.1.1 on 2024-11-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('user_id', models.OneToOneField(db_column='user_id', editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paypal', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('paypal_merchant_id', models.CharField(max_length=255, unique=True)),
                ('paypal_linked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_paypal',
            },
        ),
    ]
