# Generated by Django 5.1.1 on 2024-10-03 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='assumee_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
