# Generated by Django 5.1.1 on 2024-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wall_amnt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
