# Generated by Django 5.1.1 on 2024-11-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_transaction_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlisting',
            name='list_id',
            field=models.ForeignKey(blank=True, db_column='list_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.listing'),
        ),
        migrations.AlterField(
            model_name='orderlisting',
            name='offer_id',
            field=models.ForeignKey(blank=True, db_column='offer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.offer'),
        ),
        migrations.AlterField(
            model_name='orderlisting',
            name='order_udpated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
