# Generated by Django 5.1.1 on 2024-12-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_refundrequest_paypal_refund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wall_amnt',
            field=models.IntegerField(default=0),
        ),
    ]
