# Generated by Django 5.1.1 on 2025-01-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_wallet_wall_amnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='list_id',
            field=models.ForeignKey(db_column='list_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.listing'),
        ),
    ]
