# Generated by Django 5.1.1 on 2024-10-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_offer_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
