# Generated by Django 5.1.1 on 2024-11-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_orderlisting_list_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlisting',
            name='order_udpated_at',
        ),
        migrations.AddField(
            model_name='orderlisting',
            name='order_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
