# Generated by Django 5.1.1 on 2024-10-11 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_offer_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wall_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('wall_amnt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='list_id',
            field=models.ForeignKey(db_column='list_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='base.listing'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to=settings.AUTH_USER_MODEL),
        ),
    ]
