# Generated by Django 5.1.1 on 2025-01-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rating_list_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
