# Generated by Django 5.1.1 on 2024-11-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_orderlisting_order_udpated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='transaction_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='capture_id',
            new_name='transaction_paypal_capture_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderlisting',
            name='order_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_listing', to='base.orderlisting'),
        ),
    ]
