# Generated by Django 5.1.1 on 2025-01-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='list_id',
            field=models.ForeignKey(db_column='list_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='base.listing'),
        ),
    ]
