# Generated by Django 5.1.1 on 2024-11-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_amount_transaction_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(default='COMPLETED', max_length=50),
        ),
    ]
