# Generated by Django 5.1.1 on 2024-10-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_wallet_alter_listing_user_id_alter_offer_list_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wallet',
            table='wallet',
        ),
    ]
