# Generated by Django 5.1.1 on 2024-10-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_wallet_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-chatmess_created_at']},
        ),
    ]
