# Generated by Django 5.1.1 on 2024-10-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
    ]
