# Generated by Django 5.1.1 on 2024-11-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_transaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
