# Generated by Django 5.1.1 on 2024-11-18 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_useraccount_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reviewer',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
