# Generated by Django 5.1.1 on 2024-10-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chatmess_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
