# Generated by Django 5.1.1 on 2024-11-25 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_follow_follower_id_alter_follow_following_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='user_app_declined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='user_reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.JSONField(null=True),
        ),
    ]
