# Generated by Django 5.1.1 on 2024-10-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='reset_token',
            field=models.CharField(),
        ),
    ]
