# Generated by Django 5.1.1 on 2024-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_passwordresettoken_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_prof_mobile',
            field=models.CharField(max_length=13),
        ),
    ]
